import 'jewish_holiday.dart';

class JewishHolidaysData {
  static List<JewishHoliday> getHolidays() => [
    // 2025
    JewishHoliday(hebrewName: 'ערב פסח', date: DateTime(2025, 4, 12), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'פסח', date: DateTime(2025, 4, 13), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2025, 4, 14), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2025, 4, 15), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2025, 4, 16), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2025, 4, 17), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'שביעי של פסח', date: DateTime(2025, 4, 18), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'אחרון של פסח', date: DateTime(2025, 4, 19), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'יום השואה', date: DateTime(2025, 4, 24), type: HolidayType.special),
    JewishHoliday(hebrewName: 'יום הזיכרון', date: DateTime(2025, 5, 1), type: HolidayType.special),
    JewishHoliday(hebrewName: 'יום העצמאות', date: DateTime(2025, 5, 2), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ל"ג בעומר', date: DateTime(2025, 5, 16), type: HolidayType.special),
    JewishHoliday(hebrewName: 'ערב שבועות', date: DateTime(2025, 6, 1), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'שבועות', date: DateTime(2025, 6, 2), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'צום י"ז בתמוז', date: DateTime(2025, 7, 13), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'תשעה באב', date: DateTime(2025, 8, 3), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'ערב ראש השנה', date: DateTime(2025, 9, 22), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'ראש השנה', date: DateTime(2025, 9, 23), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ראש השנה', date: DateTime(2025, 9, 24), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'צום גדליה', date: DateTime(2025, 9, 25), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'ערב יום כיפור', date: DateTime(2025, 10, 1), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'יום כיפור', date: DateTime(2025, 10, 2), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ערב סוכות', date: DateTime(2025, 10, 6), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'סוכות', date: DateTime(2025, 10, 7), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2025, 10, 8), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2025, 10, 9), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2025, 10, 10), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2025, 10, 11), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2025, 10, 12), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'הושענא רבה', date: DateTime(2025, 10, 13), type: HolidayType.special),
    JewishHoliday(hebrewName: 'שמיני עצרת', date: DateTime(2025, 10, 14), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'שמחת תורה', date: DateTime(2025, 10, 14), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 15), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 16), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 17), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 18), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 19), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 20), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 21), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2025, 12, 22), type: HolidayType.special),

    // 2026
    JewishHoliday(hebrewName: 'צום עשרה בטבת', date: DateTime(2026, 1, 1), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'ט"ו בשבט', date: DateTime(2026, 2, 3), type: HolidayType.special),
    JewishHoliday(hebrewName: 'ערב פורים', date: DateTime(2026, 3, 2), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'פורים', date: DateTime(2026, 3, 3), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ערב פסח', date: DateTime(2026, 4, 1), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'פסח', date: DateTime(2026, 4, 2), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2026, 4, 3), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2026, 4, 4), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2026, 4, 5), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד פסח', date: DateTime(2026, 4, 6), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'שביעי של פסח', date: DateTime(2026, 4, 7), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'אחרון של פסח', date: DateTime(2026, 4, 8), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'יום השואה', date: DateTime(2026, 4, 14), type: HolidayType.special),
    JewishHoliday(hebrewName: 'יום הזיכרון', date: DateTime(2026, 4, 21), type: HolidayType.special),
    JewishHoliday(hebrewName: 'יום העצמאות', date: DateTime(2026, 4, 22), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ל"ג בעומר', date: DateTime(2026, 5, 6), type: HolidayType.special),
    JewishHoliday(hebrewName: 'ערב שבועות', date: DateTime(2026, 5, 21), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'שבועות', date: DateTime(2026, 5, 22), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'צום י"ז בתמוז', date: DateTime(2026, 7, 2), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'תשעה באב', date: DateTime(2026, 7, 23), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'ערב ראש השנה', date: DateTime(2026, 9, 11), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'ראש השנה', date: DateTime(2026, 9, 12), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ראש השנה', date: DateTime(2026, 9, 13), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'צום גדליה', date: DateTime(2026, 9, 14), type: HolidayType.fast),
    JewishHoliday(hebrewName: 'ערב יום כיפור', date: DateTime(2026, 9, 20), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'יום כיפור', date: DateTime(2026, 9, 21), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'ערב סוכות', date: DateTime(2026, 9, 25), type: HolidayType.eve),
    JewishHoliday(hebrewName: 'סוכות', date: DateTime(2026, 9, 26), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2026, 9, 27), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2026, 9, 28), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2026, 9, 29), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2026, 9, 30), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'חול המועד סוכות', date: DateTime(2026, 10, 1), type: HolidayType.intermediateDays),
    JewishHoliday(hebrewName: 'הושענא רבה', date: DateTime(2026, 10, 2), type: HolidayType.special),
    JewishHoliday(hebrewName: 'שמיני עצרת / שמחת תורה', date: DateTime(2026, 10, 3), type: HolidayType.holiday),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 5), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 6), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 7), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 8), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 9), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 10), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 11), type: HolidayType.special),
    JewishHoliday(hebrewName: 'חנוכה', date: DateTime(2026, 12, 12), type: HolidayType.special),
  ];

  static Map<DateTime, List<JewishHoliday>> get holidayMap {
    final map = <DateTime, List<JewishHoliday>>{};
    for (final h in getHolidays()) {
      final key = DateTime(h.date.year, h.date.month, h.date.day);
      map.putIfAbsent(key, () => []).add(h);
    }
    return map;
  }
}
